/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWorkspacesIndexRouteImport } from './routes/dashboard/workspaces/index'
import { Route as DashboardWorkspacesSlugIndexRouteImport } from './routes/dashboard/workspaces/$slug/index'
import { Route as DashboardSettingsSpecsIndexRouteImport } from './routes/dashboard/settings/specs/index'
import { Route as DashboardSettingsProxyIndexRouteImport } from './routes/dashboard/settings/proxy/index'
import { Route as DashboardSettingsGitappsIndexRouteImport } from './routes/dashboard/settings/gitapps/index'
import { Route as DashboardWorkspacesSlugIslugRouteImport } from './routes/dashboard/workspaces/$slug/$islug'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWorkspacesIndexRoute =
  DashboardWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWorkspacesSlugIndexRoute =
  DashboardWorkspacesSlugIndexRouteImport.update({
    id: '/workspaces/$slug/',
    path: '/workspaces/$slug/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsSpecsIndexRoute =
  DashboardSettingsSpecsIndexRouteImport.update({
    id: '/settings/specs/',
    path: '/settings/specs/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsProxyIndexRoute =
  DashboardSettingsProxyIndexRouteImport.update({
    id: '/settings/proxy/',
    path: '/settings/proxy/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsGitappsIndexRoute =
  DashboardSettingsGitappsIndexRouteImport.update({
    id: '/settings/gitapps/',
    path: '/settings/gitapps/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWorkspacesSlugIslugRoute =
  DashboardWorkspacesSlugIslugRouteImport.update({
    id: '/workspaces/$slug/$islug',
    path: '/workspaces/$slug/$islug',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/dashboard/workspaces/': typeof DashboardWorkspacesIndexRoute
  '/dashboard/workspaces/$slug/$islug': typeof DashboardWorkspacesSlugIslugRoute
  '/dashboard/settings/gitapps/': typeof DashboardSettingsGitappsIndexRoute
  '/dashboard/settings/proxy/': typeof DashboardSettingsProxyIndexRoute
  '/dashboard/settings/specs/': typeof DashboardSettingsSpecsIndexRoute
  '/dashboard/workspaces/$slug/': typeof DashboardWorkspacesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesIndexRoute
  '/dashboard/workspaces/$slug/$islug': typeof DashboardWorkspacesSlugIslugRoute
  '/dashboard/settings/gitapps': typeof DashboardSettingsGitappsIndexRoute
  '/dashboard/settings/proxy': typeof DashboardSettingsProxyIndexRoute
  '/dashboard/settings/specs': typeof DashboardSettingsSpecsIndexRoute
  '/dashboard/workspaces/$slug': typeof DashboardWorkspacesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/dashboard/workspaces/': typeof DashboardWorkspacesIndexRoute
  '/dashboard/workspaces/$slug/$islug': typeof DashboardWorkspacesSlugIslugRoute
  '/dashboard/settings/gitapps/': typeof DashboardSettingsGitappsIndexRoute
  '/dashboard/settings/proxy/': typeof DashboardSettingsProxyIndexRoute
  '/dashboard/settings/specs/': typeof DashboardSettingsSpecsIndexRoute
  '/dashboard/workspaces/$slug/': typeof DashboardWorkspacesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/dashboard/'
    | '/login/'
    | '/register/'
    | '/dashboard/workspaces/'
    | '/dashboard/workspaces/$slug/$islug'
    | '/dashboard/settings/gitapps/'
    | '/dashboard/settings/proxy/'
    | '/dashboard/settings/specs/'
    | '/dashboard/workspaces/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/workspaces'
    | '/dashboard/workspaces/$slug/$islug'
    | '/dashboard/settings/gitapps'
    | '/dashboard/settings/proxy'
    | '/dashboard/settings/specs'
    | '/dashboard/workspaces/$slug'
  id:
    | '__root__'
    | '/dashboard'
    | '/dashboard/'
    | '/login/'
    | '/register/'
    | '/dashboard/workspaces/'
    | '/dashboard/workspaces/$slug/$islug'
    | '/dashboard/settings/gitapps/'
    | '/dashboard/settings/proxy/'
    | '/dashboard/settings/specs/'
    | '/dashboard/workspaces/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/workspaces/': {
      id: '/dashboard/workspaces/'
      path: '/workspaces'
      fullPath: '/dashboard/workspaces/'
      preLoaderRoute: typeof DashboardWorkspacesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/workspaces/$slug/': {
      id: '/dashboard/workspaces/$slug/'
      path: '/workspaces/$slug'
      fullPath: '/dashboard/workspaces/$slug/'
      preLoaderRoute: typeof DashboardWorkspacesSlugIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/specs/': {
      id: '/dashboard/settings/specs/'
      path: '/settings/specs'
      fullPath: '/dashboard/settings/specs/'
      preLoaderRoute: typeof DashboardSettingsSpecsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/proxy/': {
      id: '/dashboard/settings/proxy/'
      path: '/settings/proxy'
      fullPath: '/dashboard/settings/proxy/'
      preLoaderRoute: typeof DashboardSettingsProxyIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/gitapps/': {
      id: '/dashboard/settings/gitapps/'
      path: '/settings/gitapps'
      fullPath: '/dashboard/settings/gitapps/'
      preLoaderRoute: typeof DashboardSettingsGitappsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/workspaces/$slug/$islug': {
      id: '/dashboard/workspaces/$slug/$islug'
      path: '/workspaces/$slug/$islug'
      fullPath: '/dashboard/workspaces/$slug/$islug'
      preLoaderRoute: typeof DashboardWorkspacesSlugIslugRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardWorkspacesIndexRoute: typeof DashboardWorkspacesIndexRoute
  DashboardWorkspacesSlugIslugRoute: typeof DashboardWorkspacesSlugIslugRoute
  DashboardSettingsGitappsIndexRoute: typeof DashboardSettingsGitappsIndexRoute
  DashboardSettingsProxyIndexRoute: typeof DashboardSettingsProxyIndexRoute
  DashboardSettingsSpecsIndexRoute: typeof DashboardSettingsSpecsIndexRoute
  DashboardWorkspacesSlugIndexRoute: typeof DashboardWorkspacesSlugIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardWorkspacesIndexRoute: DashboardWorkspacesIndexRoute,
  DashboardWorkspacesSlugIslugRoute: DashboardWorkspacesSlugIslugRoute,
  DashboardSettingsGitappsIndexRoute: DashboardSettingsGitappsIndexRoute,
  DashboardSettingsProxyIndexRoute: DashboardSettingsProxyIndexRoute,
  DashboardSettingsSpecsIndexRoute: DashboardSettingsSpecsIndexRoute,
  DashboardWorkspacesSlugIndexRoute: DashboardWorkspacesSlugIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
